# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YXGame' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Masonry'
   pod 'MBProgressHUD'
   pod 'MJExtension', '~> 3.0.13'

  # Pods for YXGame

end
