# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YX2048' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'AFNetworking', '~> 3.2.1'
  # Pods for YX2048

end
